name: Translation Updater
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: actions/checkout@v3
      - uses: ./action
        with:
          project_id: ${{secrets.PROJECT_ID}}
          token: ${{secrets.TOKEN}}
          mongo_url: ${{secrets.MONGO_URL}}
